### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by swvalenti194** [bugsounet/MMM-News#10]
git pull and npm install says it updated packages but when I check the version in the package.json it shows 2.0.0?  What am I doing wrong?   Thanks

`pi@raspberrypi:~ $ cd MagicMirror
pi@raspberrypi:~/MagicMirror $ cd modules
pi@raspberrypi:~/MagicMirror/modules $ cd MMM-News
pi@raspberrypi:~/MagicMirror/modules/MMM-News $ git pull
Updating 081fcb2..bff080d
pi@raspberrypi:~/MagicMirror/modules/MMM-News $ npm install
audited 95 packages in 3.8s
found 0 vulnerabilities`

**Comment by bugsounet** [comment]
maybe retry installing ?

delete MMM-News
and reinstall it

it's weird...

**Comment by swvalenti194** [comment]
@bugsounet that worked thank you!
