### ISSUE TITLE
Remove Source from Title?

### ISSUE THREAD

**Issue by rustypasini** [bugsounet/MMM-News#13]
First, outstanding module!  Thanks for your work on it.

It appears that %TITLE% includes the Source Name at the end for some of the articles.  NewsAPI is doing it in the data they send.  It only happens with some of the sources, too (CNN, Fox News, Engadget...  but not Google News).

![image](https://user-images.githubusercontent.com/38335873/87717463-6acf5200-c77e-11ea-8701-4f5f84cf1672.png)

Is it possible to add the following to MMM-News:

* Strip the Source Name from %TITLE% if it exists
* Create an option in the configuration to toggle this on & off

Thanks for considering!

**Comment by bugsounet** [comment]
hi, sorry for very late response ...
but it's not possible actually, New api return it in the title and this complex to determinate it for deleting
