### ISSUE TITLE
MMM-News - Error with an nginx Proxy

### ISSUE THREAD

**Issue by fbr1969** [bugsounet/MMM-News#8]
Hi,

I test actually the MMM-News module. He works fine on my local Area Network. 
I would like now to acced to my private MagicMirror server (located at home) on internet, so I use an nginx  proxy. It work fine with MMirror and a lot of different modules, but I have an error message and nothing on screen with MMM-News.
In the nginx error.log I found :

`2020/04/17 14:45:10 [error] 19273#19273: *206 open() "/var/www/html/modules/MMM-News/template.html" failed (2: No such file or directory), client: xx.xx.xxx.x, server: myserver.fr, request: "GET /modules/MMM-News/template.html HTTP/1.1", host: "myserver.fr", referrer: "https://myserver.fr/mmirror/"`

My nginx configuration is 

location /mmirror/ {
        proxy_pass              http://192.168.yy.yy:8080/; <--- Magic Mirror server
        proxy_pass_request_headers on;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        # Disable buffering when the nginx proxy gets very resource heavy upon streaming
        proxy_buffering off;
        }

        location /socket.io {
                # Proxy Magic Mirror Websockets traffic
                proxy_pass http://192.168.yy.yy:8080; <--- Magic Mirror server
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Protocol $scheme;
                proxy_set_header X-Forwarded-Host $http_host;
        }

Is somebody have any idea of this problem ?

Best regards

**Comment by eouia** [comment]
Hmmm.
This mirror would try lookup to read `[CURRENT LOCATION]/modules/MMM-News/template.html`. So your Nginx proxy should serve that URL accessible. 

Or modify source to point real URL to serve.

https://github.com/eouia/MMM-News/blob/081fcb219b3bba459d5486b6e1836e8dc429e60e/MMM-News.js#L365

**Comment by fbr1969** [comment]
Thank for your help, but I don't want to touch the source code. It's strange because my Nginx configuration works with a lot of other module like MMM-GoogleMapsTraffic, MMM-Paris-RATP-PG, MMM-AirParif.

**Comment by bugsounet** [comment]
Bonjour, je vais essayer de fixer ce problème dans quelques jours.

J'ai repris le projet en main (comme pas mal d'autre modules !)
J'ai repérer quelques bugs a corriger ;)

un peu de patience encore ;)
Je laisse l'issue ouverte et je reviens vers vous dès que les changements sont effectués.

**Comment by fbr1969** [comment]
Merci. Je me demande si il n'y a pas une fuite mémoire aussi sur ce module. Je vais essayer de vérifier.

**Comment by bugsounet** [comment]
beaucoup d'erreur de codage, je suis en train de résoudre cela (sur la branch `dev`)

**Comment by bugsounet** [comment]
@fbr1969: j'ai mis en ligne la version `dev` sur le `master`

Pouvez-vous me dire si le problème est corrigé ? (je ne suis pas totalement sur)

**Comment by fbr1969** [comment]
Hello. Testé a l'instant et ça fonctionne ! Bravo !

**Comment by bugsounet** [comment]
parfait dans ce cas ! :)
Je ferme l'issue
